;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 6
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env11,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env12,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env3,@env0,@env13
	.byte $00
	.byte $b0 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0b
	.word @env5,@env0,@env14
	.byte $00
	.byte $b0 ;instrument $0c
	.word @env6,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0d
	.word @env7,@env0,@env15
	.byte $00
	.byte $b0 ;instrument $0e
	.word @env8,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0f
	.word @env9,@env0,@env16
	.byte $00
	.byte $b0 ;instrument $10
	.word @env10,@env0,@env16
	.byte $00
	.byte $b0 ;instrument $11
	.word @env7,@env0,@env15
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c4,$00,$00
@env2:
	.byte $c4,$c7,$c9,$ca,$cb,$cc,$cb,$c9,$00,$07
@env3:
	.byte $c3,$02,$c2,$00,$02
@env4:
	.byte $c5,$c3,$c2,$c1,$c0,$00,$04
@env5:
	.byte $c0,$c1,$c2,$c3,$c4,$c4,$c5,$c4,$c4,$c3,$c3,$c2,$c1,$00,$0c
@env6:
	.byte $c6,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c0,$c1,$c0,$00,$0b
@env7:
	.byte $c2,$c1,$c0,$00,$02
@env8:
	.byte $c3,$c2,$c2,$c1,$c0,$00,$04
@env9:
	.byte $c2,$c8,$c6,$c4,$c2,$c1,$c0,$00,$06
@env10:
	.byte $c0,$c0,$c1,$c2,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@env11:
	.byte $c0,$c1,$c2,$c3,$c4,$c5,$c7,$c9,$00,$07
@env12:
	.byte $c9,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$07
@env13:
	.byte $eb,$ff,$02,$ff,$00,$03
@env14:
	.byte $ba,$b4,$b4,$00,$02
@env15:
	.byte $c5,$d4,$d7,$da,$da,$d7,$00,$05
@env16:
	.byte $cd,$d2,$d3,$d0,$d0,$d3,$d2,$d2,$00,$04


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$28,$85,$30,$85,$36,$85,$31,$29,$29,$29,$30,$85,$36,$85,$2c
	.byte $85,$28,$85,$30,$85,$36,$85,$30,$85,$28,$85,$26,$85,$28,$85,$00
	.byte $85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref1:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref3:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$04
@ref5:
	.byte $82,$52,$4e,$4a,$48,$44,$40,$3c,$3a,$36,$32,$30,$2c,$28,$24,$00
	.byte $e1
@song1ch0loop:
@ref6:
	.byte $81
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@ref7:
	.byte $f9,$85
@song1ch1loop:
@ref8:
	.byte $81
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@ref9:
	.byte $f9,$85
@song1ch2loop:
@ref10:
	.byte $81
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@ref11:
	.byte $9d,$84,$19,$00,$db
@song1ch3loop:
@ref12:
	.byte $81
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@ref13:
	.byte $f9,$85
@song1ch4loop:
@ref14:
	.byte $81
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$02
@ref15:
	.byte $82,$1a,$1e,$22,$24,$28,$2c,$30,$32,$36,$3a,$3c,$40,$44,$48,$4a
	.byte $4e,$52,$54,$58,$5c,$60,$62,$00,$d1
@song2ch0loop:
@ref16:
	.byte $81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref17:
	.byte $f9,$85
@song2ch1loop:
@ref18:
	.byte $81
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref19:
	.byte $f9,$85
@song2ch2loop:
@ref20:
	.byte $81
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref21:
	.byte $f9,$85
@song2ch3loop:
@ref22:
	.byte $81
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref23:
	.byte $f9,$85
@song2ch4loop:
@ref24:
	.byte $81
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$08
@song3ch0loop:
@ref25:
	.byte $f9,$85
@ref26:
	.byte $a1
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref27:
	.byte $86,$03,$01,$03,$01,$0a,$10,$0b,$01,$03,$00,$85,$03,$01,$03,$01
	.byte $0a,$10,$0b,$01,$07,$00,$85,$03,$01,$03,$01,$0a,$10,$0b,$01,$03
	.byte $00,$85,$03,$00,$81
@ref28:
	.byte $0b,$00,$85,$0b,$01,$03,$00,$87
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref29:
	.byte $f9,$85
@ref30:
	.byte $a1
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref31:
	.byte $88,$04,$85,$04,$16,$85,$05,$05,$04,$16,$e1
@ref32:
	.byte $a1
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref33:
	.byte $f9,$85
@ref34:
	.byte $a1
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$03
@song4ch0loop:
@ref35:
	.byte $8a,$4a,$95,$52,$85,$4e,$85,$4a,$8d,$4e,$8d,$52,$8d,$54,$85,$52
	.byte $8d,$4e,$8d
@ref36:
	.byte $4a,$95,$52,$85,$4e,$85,$4a,$8d,$4e,$8d,$52,$8d,$54,$85,$52,$9d
@ref37:
	.byte $4a,$95,$52,$85,$4e,$85,$4a,$8d,$4e,$8d,$52,$8d,$54,$85,$52,$8d
	.byte $4e,$8d
@ref38:
	.byte $4a,$95,$52,$85,$4e,$85,$4a,$8d,$44,$8d,$48,$8d,$4e,$85,$4a,$9d
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref39:
	.byte $90,$1a,$95,$22,$85,$1e,$85,$1a,$8d,$1e,$8d,$22,$8d,$24,$85,$22
	.byte $8d,$1e,$8d
@ref40:
	.byte $1a,$95,$22,$85,$1e,$85,$1a,$8d,$1e,$8d,$22,$8d,$24,$85,$22,$9d
@ref41:
	.byte $1a,$95,$22,$85,$1e,$85,$1a,$8d,$1e,$8d,$22,$8d,$24,$85,$22,$8d
	.byte $1e,$8d
@ref42:
	.byte $1a,$95,$22,$85,$1e,$85,$1a,$8d,$14,$8d,$18,$8d,$1e,$85,$1a,$9d
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref43:
	.byte $8c,$1a,$95,$22,$85,$1e,$85,$1a,$8d,$1e,$8d,$22,$8d,$24,$85,$22
	.byte $8d,$1e,$8d
	.byte $ff,$10
	.word @ref40
	.byte $ff,$12
	.word @ref41
	.byte $ff,$10
	.word @ref42
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref47:
	.byte $8e,$18,$91,$19,$18,$85,$90,$08,$95,$8e,$1a,$8d,$1a,$8d,$1a,$85
	.byte $90,$08,$9d
	.byte $ff,$0f
	.word @ref47
	.byte $ff,$0f
	.word @ref47
	.byte $ff,$0f
	.word @ref47
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref51:
	.byte $f9,$85
@ref52:
	.byte $f9,$85
@ref53:
	.byte $f9,$85
@ref54:
	.byte $f9,$85
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$06
@song5ch0loop:
@ref55:
	.byte $92,$32,$89,$36,$3a,$44,$85,$40,$85,$44,$85,$49,$4b,$48,$85,$44
	.byte $85
@ref56:
	.byte $32,$89,$36,$3a,$44,$85,$40,$85,$41,$45,$49,$45,$40,$85,$36,$85
@ref57:
	.byte $32,$89,$36,$3a,$44,$85,$40,$85,$44,$85,$49,$4b,$48,$85,$44,$85
@ref58:
	.byte $32,$89,$36,$3a,$44,$85,$40,$85,$36,$85,$30,$85,$32,$8d
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@song5ch1loop:
@ref59:
	.byte $94,$32,$89,$36,$3a,$44,$85,$40,$85,$44,$85,$49,$4b,$48,$85,$44
	.byte $85
	.byte $ff,$10
	.word @ref56
	.byte $ff,$10
	.word @ref57
	.byte $ff,$0e
	.word @ref58
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@song5ch2loop:
@ref63:
	.byte $bf
@ref64:
	.byte $bf
@ref65:
	.byte $bf
@ref66:
	.byte $bf
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@song5ch3loop:
@ref67:
	.byte $96,$20,$85,$20,$85,$0e,$85,$20,$85,$20,$85,$20,$85,$0e,$85,$20
	.byte $85
@ref68:
	.byte $20,$85,$20,$85,$0e,$85,$20,$85,$20,$85,$20,$85,$0e,$85,$20,$85
	.byte $ff,$10
	.word @ref68
	.byte $ff,$10
	.word @ref68
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@song5ch4loop:
@ref71:
	.byte $bf
@ref72:
	.byte $bf
@ref73:
	.byte $bf
@ref74:
	.byte $bf
	.byte $fd
	.word @song5ch4loop
