;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $83,$b1,$84,$67,$85,$01,$01,$83,$b2,$84,$3f,$01,$84,$0c,$01,$83
	.byte $b1,$84,$ef,$85,$00,$01,$83,$b2,$01,$83,$b3,$84,$e1,$00
